name: Auto Add Not Based On Develop Label
on:
  pull_request:
    types: [ opened, reopend ]
    branches-ignore:
      - 'release/**'
      - develop

jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assign Labels
        uses: RobinJesba/GitHub-Labeler-Action@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS_TO_ADD: 'not based on develop'
