name: Auto Add Not Based On Develop Label
on:
  pull_request:
    types: [ opened, reopend ]
    branches-ignore:
      - 'release/**'
      - develop

jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            'not based on develop'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
