name: Auto-assign PR Reviewer

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]
        branches-ignore:
          - 'release/**'
jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: 'Auto-assign PR Reviewer'
              uses: zhgchgli0718/auto-assign-issue@v2
              with:
                  repo-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }} 
                  targetTeamA: 'ios-a' # The name of the team to which the target assignees belong
                  targetTeamB: 'ios-b' # The name of the team to which the target assignees belong
                  numOfAssignee: 2 # Number of random assignees
                  excludeAssignees: '' # Optional, Users to be excluded from being assigned as reviewers (comma-separated)
